name: macOS CD

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Remove Perl
        run: |
          brew uninstall --ignore-dependencies perl
      - name: Check Perl
        run: |
          which perl
      - name: yarn install
        run: |
          yarn install-all
      - name: Publish macOS
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          yarn publish-app-mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
